#!/bin/bash

# python src/main.py --sim 0 --data mesonet_pressure --single_test 1 --step_size 1 --window_size 600 --split_variance 0 --M 2 --recursion 1 --candidate_recursion 1 --optim_type Boyd --lam 5e-2 --results_fldr_name pressure_storm --data_path ../data/out_pressure --data_fname pressure_storm_0_unprocessed_data.csv --results_filename pressure_storm_0.csv --save_test_stat 1 --train_percent 0.1 --base_M 4 --log_pvals 1 --post_window_size 25 --linkage single --thresh_const 1.2
 
# python src/main.py --sim 0 --data mesonet_pressure --single_test 1 --step_size 1 --window_size 600 --split_variance 0 --M 2 --recursion 1 --candidate_recursion 1 --optim_type Boyd --lam 5e-2 --results_fldr_name pressure_storm --data_path ../data/out_pressure --data_fname pressure_storm_47_unprocessed_data.csv --results_filename pressure_storm_47.csv --save_test_stat 1 --train_percent 0.1 --base_M 4 --log_pvals 1 --post_window_size 25 --linkage single --thresh_const 1.2
 
# python src/main.py --sim 0 --data mesonet_pressure --single_test 1 --step_size 1 --window_size 600 --split_variance 0 --M 2 --recursion 1 --candidate_recursion 1 --optim_type Boyd --lam 5e-2 --results_fldr_name pressure_storm --data_path ../data/out_pressure --data_fname pressure_storm_51_unprocessed_data.csv --results_filename pressure_storm_51.csv --save_test_stat 1 --train_percent 0.1 --base_M 4 --log_pvals 1 --post_window_size 25 --linkage single --thresh_const 1.2
 
# python src/main.py --sim 0 --data mesonet_pressure --single_test 1 --step_size 1 --window_size 600 --split_variance 0 --M 2 --recursion 1 --candidate_recursion 1 --optim_type Boyd --lam 5e-2 --results_fldr_name pressure_storm --data_path ../data/out_pressure --data_fname pressure_storm_103_unprocessed_data.csv --results_filename pressure_storm_103.csv --save_test_stat 1 --train_percent 0.1 --base_M 4 --log_pvals 1 --post_window_size 25 --linkage single --thresh_const 1.2
 
# python src/main.py --sim 0 --data mesonet_pressure --single_test 1 --step_size 1 --window_size 600 --split_variance 0 --M 2 --recursion 1 --candidate_recursion 1 --optim_type Boyd --lam 5e-2 --results_fldr_name pressure_storm --data_path ../data/out_pressure --data_fname pressure_storm_104_unprocessed_data.csv --results_filename pressure_storm_104.csv --save_test_stat 1 --train_percent 0.1 --base_M 4 --log_pvals 1 --post_window_size 25 --linkage single --thresh_const 1.2
 
# python src/main.py --sim 0 --data mesonet_pressure --single_test 1 --step_size 1 --window_size 600 --split_variance 0 --M 2 --recursion 1 --candidate_recursion 1 --optim_type Boyd --lam 5e-2 --results_fldr_name pressure_storm --data_path ../data/out_pressure --data_fname pressure_storm_105_unprocessed_data.csv --results_filename pressure_storm_105.csv --save_test_stat 1 --train_percent 0.1 --base_M 4 --log_pvals 1 --post_window_size 25 --linkage single --thresh_const 1.2
 
# python src/main.py --sim 0 --data mesonet_pressure --single_test 1 --step_size 1 --window_size 600 --split_variance 0 --M 2 --recursion 1 --candidate_recursion 1 --optim_type Boyd --lam 5e-2 --results_fldr_name pressure_storm --data_path ../data/out_pressure --data_fname pressure_storm_107_unprocessed_data.csv --results_filename pressure_storm_107.csv --save_test_stat 1 --train_percent 0.1 --base_M 4 --log_pvals 1 --post_window_size 25 --linkage single --thresh_const 1.2
 
# python src/main.py --sim 0 --data mesonet_pressure --single_test 1 --step_size 1 --window_size 600 --split_variance 0 --M 2 --recursion 1 --candidate_recursion 1 --optim_type Boyd --lam 5e-2 --results_fldr_name pressure_storm --data_path ../data/out_pressure --data_fname pressure_storm_127_unprocessed_data.csv --results_filename pressure_storm_127.csv --save_test_stat 1 --train_percent 0.1 --base_M 4 --log_pvals 1 --post_window_size 25 --linkage single --thresh_const 1.2
 
# python src/main.py --sim 0 --data mesonet_pressure --single_test 1 --step_size 1 --window_size 600 --split_variance 0 --M 2 --recursion 1 --candidate_recursion 1 --optim_type Boyd --lam 5e-2 --results_fldr_name pressure_storm --data_path ../data/out_pressure --data_fname pressure_storm_137_unprocessed_data.csv --results_filename pressure_storm_137.csv --save_test_stat 1 --train_percent 0.1 --base_M 4 --log_pvals 1 --post_window_size 25 --linkage single --thresh_const 1.2
 
# python src/main.py --sim 0 --data mesonet_pressure --single_test 1 --step_size 1 --window_size 600 --split_variance 0 --M 2 --recursion 1 --candidate_recursion 1 --optim_type Boyd --lam 5e-2 --results_fldr_name pressure_storm --data_path ../data/out_pressure --data_fname pressure_storm_144_unprocessed_data.csv --results_filename pressure_storm_144.csv --save_test_stat 1 --train_percent 0.1 --base_M 4 --log_pvals 1 --post_window_size 25 --linkage single --thresh_const 1.2
 
# python src/main.py --sim 0 --data mesonet_pressure --single_test 1 --step_size 1 --window_size 600 --split_variance 0 --M 2 --recursion 1 --candidate_recursion 1 --optim_type Boyd --lam 5e-2 --results_fldr_name pressure_storm --data_path ../data/out_pressure --data_fname pressure_storm_153_unprocessed_data.csv --results_filename pressure_storm_153.csv --save_test_stat 1 --train_percent 0.1 --base_M 4 --log_pvals 1 --post_window_size 25 --linkage single --thresh_const 1.2
 
# python src/main.py --sim 0 --data mesonet_pressure --single_test 1 --step_size 1 --window_size 600 --split_variance 0 --M 2 --recursion 1 --candidate_recursion 1 --optim_type Boyd --lam 5e-2 --results_fldr_name pressure_storm --data_path ../data/out_pressure --data_fname pressure_storm_162_unprocessed_data.csv --results_filename pressure_storm_162.csv --save_test_stat 1 --train_percent 0.1 --base_M 4 --log_pvals 1 --post_window_size 25 --linkage single --thresh_const 1.2
 
# python src/main.py --sim 0 --data mesonet_pressure --single_test 1 --step_size 1 --window_size 600 --split_variance 0 --M 2 --recursion 1 --candidate_recursion 1 --optim_type Boyd --lam 5e-2 --results_fldr_name pressure_storm --data_path ../data/out_pressure --data_fname pressure_storm_163_unprocessed_data.csv --results_filename pressure_storm_163.csv --save_test_stat 1 --train_percent 0.1 --base_M 4 --log_pvals 1 --post_window_size 25 --linkage single --thresh_const 1.2
 
# python src/main.py --sim 0 --data mesonet_pressure --single_test 1 --step_size 1 --window_size 600 --split_variance 0 --M 2 --recursion 1 --candidate_recursion 1 --optim_type Boyd --lam 5e-2 --results_fldr_name pressure_storm --data_path ../data/out_pressure --data_fname pressure_storm_173_unprocessed_data.csv --results_filename pressure_storm_173.csv --save_test_stat 1 --train_percent 0.1 --base_M 4 --log_pvals 1 --post_window_size 25 --linkage single --thresh_const 1.2
 
# python src/main.py --sim 0 --data mesonet_pressure --single_test 1 --step_size 1 --window_size 600 --split_variance 0 --M 2 --recursion 1 --candidate_recursion 1 --optim_type Boyd --lam 5e-2 --results_fldr_name pressure_storm --data_path ../data/out_pressure --data_fname pressure_storm_176_unprocessed_data.csv --results_filename pressure_storm_176.csv --save_test_stat 1 --train_percent 0.1 --base_M 4 --log_pvals 1 --post_window_size 25 --linkage single --thresh_const 1.2
 
# python src/main.py --sim 0 --data mesonet_pressure --single_test 1 --step_size 1 --window_size 600 --split_variance 0 --M 2 --recursion 1 --candidate_recursion 1 --optim_type Boyd --lam 5e-2 --results_fldr_name pressure_storm --data_path ../data/out_pressure --data_fname pressure_storm_200_unprocessed_data.csv --results_filename pressure_storm_200.csv --save_test_stat 1 --train_percent 0.1 --base_M 4 --log_pvals 1 --post_window_size 25 --linkage single --thresh_const 1.2
 
# python src/main.py --sim 0 --data mesonet_pressure --single_test 1 --step_size 1 --window_size 600 --split_variance 0 --M 2 --recursion 1 --candidate_recursion 1 --optim_type Boyd --lam 5e-2 --results_fldr_name pressure_storm --data_path ../data/out_pressure --data_fname pressure_storm_201_unprocessed_data.csv --results_filename pressure_storm_201.csv --save_test_stat 1 --train_percent 0.1 --base_M 4 --log_pvals 1 --post_window_size 25 --linkage single --thresh_const 1.2
 
# python src/main.py --sim 0 --data mesonet_pressure --single_test 1 --step_size 1 --window_size 600 --split_variance 0 --M 2 --recursion 1 --candidate_recursion 1 --optim_type Boyd --lam 5e-2 --results_fldr_name pressure_storm --data_path ../data/out_pressure --data_fname pressure_storm_329_unprocessed_data.csv --results_filename pressure_storm_329.csv --save_test_stat 1 --train_percent 0.1 --base_M 4 --log_pvals 1 --post_window_size 25 --linkage single --thresh_const 1.2
 
# python src/main.py --sim 0 --data mesonet_pressure --single_test 1 --step_size 1 --window_size 600 --split_variance 0 --M 2 --recursion 1 --candidate_recursion 1 --optim_type Boyd --lam 5e-2 --results_fldr_name pressure_storm --data_path ../data/out_pressure --data_fname pressure_storm_338_unprocessed_data.csv --results_filename pressure_storm_338.csv --save_test_stat 1 --train_percent 0.1 --base_M 4 --log_pvals 1 --post_window_size 25 --linkage single --thresh_const 1.2
 
# python src/main.py --sim 0 --data mesonet_pressure --single_test 1 --step_size 1 --window_size 600 --split_variance 0 --M 2 --recursion 1 --candidate_recursion 1 --optim_type Boyd --lam 5e-2 --results_fldr_name pressure_storm --data_path ../data/out_pressure --data_fname pressure_storm_384_unprocessed_data.csv --results_filename pressure_storm_384.csv --save_test_stat 1 --train_percent 0.1 --base_M 4 --log_pvals 1 --post_window_size 25 --linkage single --thresh_const 1.2
 
# python src/main.py --sim 0 --data mesonet_pressure --single_test 1 --step_size 1 --window_size 600 --split_variance 0 --M 2 --recursion 1 --candidate_recursion 1 --optim_type Boyd --lam 5e-2 --results_fldr_name pressure_storm --data_path ../data/out_pressure --data_fname pressure_storm_386_unprocessed_data.csv --results_filename pressure_storm_386.csv --save_test_stat 1 --train_percent 0.1 --base_M 4 --log_pvals 1 --post_window_size 25 --linkage single --thresh_const 1.2
 
# python src/main.py --sim 0 --data mesonet_pressure --single_test 1 --step_size 1 --window_size 600 --split_variance 0 --M 2 --recursion 1 --candidate_recursion 1 --optim_type Boyd --lam 5e-2 --results_fldr_name pressure_storm --data_path ../data/out_pressure --data_fname pressure_storm_390_unprocessed_data.csv --results_filename pressure_storm_390.csv --save_test_stat 1 --train_percent 0.1 --base_M 4 --log_pvals 1 --post_window_size 25 --linkage single --thresh_const 1.2
 
# python src/main.py --sim 0 --data mesonet_pressure --single_test 1 --step_size 1 --window_size 600 --split_variance 0 --M 2 --recursion 1 --candidate_recursion 1 --optim_type Boyd --lam 5e-2 --results_fldr_name pressure_storm --data_path ../data/out_pressure --data_fname pressure_storm_391_unprocessed_data.csv --results_filename pressure_storm_391.csv --save_test_stat 1 --train_percent 0.1 --base_M 4 --log_pvals 1 --post_window_size 25 --linkage single --thresh_const 1.2
 
# python src/main.py --sim 0 --data mesonet_pressure --single_test 1 --step_size 1 --window_size 600 --split_variance 0 --M 2 --recursion 1 --candidate_recursion 1 --optim_type Boyd --lam 5e-2 --results_fldr_name pressure_storm --data_path ../data/out_pressure --data_fname pressure_storm_392_unprocessed_data.csv --results_filename pressure_storm_392.csv --save_test_stat 1 --train_percent 0.1 --base_M 4 --log_pvals 1 --post_window_size 25 --linkage single --thresh_const 1.2
 
# python src/main.py --sim 0 --data mesonet_pressure --single_test 1 --step_size 1 --window_size 600 --split_variance 0 --M 2 --recursion 1 --candidate_recursion 1 --optim_type Boyd --lam 5e-2 --results_fldr_name pressure_storm --data_path ../data/out_pressure --data_fname pressure_storm_398_unprocessed_data.csv --results_filename pressure_storm_398.csv --save_test_stat 1 --train_percent 0.1 --base_M 4 --log_pvals 1 --post_window_size 25 --linkage single --thresh_const 1.2
 
# python src/main.py --sim 0 --data mesonet_pressure --single_test 1 --step_size 1 --window_size 600 --split_variance 0 --M 2 --recursion 1 --candidate_recursion 1 --optim_type Boyd --lam 5e-2 --results_fldr_name pressure_storm --data_path ../data/out_pressure --data_fname pressure_storm_403_unprocessed_data.csv --results_filename pressure_storm_403.csv --save_test_stat 1 --train_percent 0.1 --base_M 4 --log_pvals 1 --post_window_size 25 --linkage single --thresh_const 1.2
 
# python src/main.py --sim 0 --data mesonet_pressure --single_test 1 --step_size 1 --window_size 600 --split_variance 0 --M 2 --recursion 1 --candidate_recursion 1 --optim_type Boyd --lam 5e-2 --results_fldr_name pressure_storm --data_path ../data/out_pressure --data_fname pressure_storm_408_unprocessed_data.csv --results_filename pressure_storm_408.csv --save_test_stat 1 --train_percent 0.1 --base_M 4 --log_pvals 1 --post_window_size 25 --linkage single --thresh_const 1.2
 
# python src/main.py --sim 0 --data mesonet_pressure --single_test 1 --step_size 1 --window_size 600 --split_variance 0 --M 2 --recursion 1 --candidate_recursion 1 --optim_type Boyd --lam 5e-2 --results_fldr_name pressure_storm --data_path ../data/out_pressure --data_fname pressure_storm_409_unprocessed_data.csv --results_filename pressure_storm_409.csv --save_test_stat 1 --train_percent 0.1 --base_M 4 --log_pvals 1 --post_window_size 25 --linkage single --thresh_const 1.2
 
python src/main.py --sim 0 --data mesonet_pressure --single_test 1 --step_size 1 --window_size 600 --split_variance 0 --M 2 --recursion 1 --candidate_recursion 1 --optim_type Boyd --lam 5e-2 --results_fldr_name pressure_storm --data_path ../data/out_pressure --data_fname pressure_storm_414_unprocessed_data.csv --results_filename pressure_storm_414.csv --save_test_stat 1 --train_percent 0.1 --base_M 4 --log_pvals 1 --post_window_size 25 --linkage single --thresh_const 1.2
 
# python src/main.py --sim 0 --data mesonet_pressure --single_test 1 --step_size 1 --window_size 600 --split_variance 0 --M 2 --recursion 1 --candidate_recursion 1 --optim_type Boyd --lam 5e-2 --results_fldr_name pressure_storm --data_path ../data/out_pressure --data_fname pressure_storm_415_unprocessed_data.csv --results_filename pressure_storm_415.csv --save_test_stat 1 --train_percent 0.1 --base_M 4 --log_pvals 1 --post_window_size 25 --linkage single --thresh_const 1.2
 
